name: CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/bake-action@v4
        with:
          targets: test
          set: |
            test.cache-from=type=gha

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/bake-action@v4
        with:
          targets: dist
          set: |
            dist.cache-from=type=gha
            dist.cache-to=type=gha,mode=max